name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: processing-playground
    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: "${{ secrets.GCLOUD_PROJECT_ID }}"
          workload_identity_provider: "projects/${{ secrets.GCLOUD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-deployer@${{ secrets.GCLOUD_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Deploy to Firebase
        run: |
          npx firebase-tools@15.22.1 deploy --only hosting:processing-playground --project ${{ secrets.GCLOUD_PROJECT_ID }}
